### PR TITLE
Don't do anything when there are only one or two words in the string.

### PR DESCRIPTION
**Pull request by peterchappell**
For single word strings we noticed that a nbsp was being prepended. That doesn't make sense. Also it wouldn't really make sense for two words (if two words don't fit in the given width, they should break).

### CODE REVIEW

**Comment by AshKyd** [comment]
Cool. I can think of times you'd potentially want to chuck a non-breaking space between two words, so maybe it's worth making this threshold a parameter as opposed to hard-coding it in.

**Comment by peterchappell** [comment]
It will always put a nbsp between the last two words (even if those two words are in a tag of their own) - only not when there are _only_ two words in total. 

Can you share some of those times when you'd want a non-breaking space between two words?

I can add the option if there's a good reason. I could also just leave it so that it works for two words but not for one (I think we could all agree that you'd never want a nbsp before one word - not as part of this plugin in any case).

**Comment by AshKyd** [comment]
I've misunderstood actually, I was thinking an option for how many non-break spaces you want would be useful, whereas this issue is about the threshold at which you start adding them.

So yeah, go for it. :)

**Comment by peterchappell** [comment]
Cool. But actually, who knows? People are strange... Also it's really easy to make it an option with the default as two. Also, there is an option for using other characters as your nbsp (including more than one nbsp).

I should update the readme too.

**Comment by blakebutcher** [comment]
What is the reason for removing the /dist/ files?

**Comment by peterchappell** [comment]
Thanks @blakebutcher. I forgot to do a build. Done now and updated the readme.

**Comment by AshKyd** [comment]
Ah ha! I'd assumed that was a deliberate ploy. Good spotting, @blakebutcher.

**Comment by peterchappell** [comment]
So if y'all are okay with it now I'll do a release soon...

**Comment by blakebutcher** [comment]
All good. Where is the approve button?

**Comment by adritek** [comment]
Looks great @peterchappell

**Pull request merged**
